title: VoltMX Design Specs
description: Design specifications
url: ""         # set if you have a custom domain
baseurl: ""     # set to "/<repo>" if publishing from the repo root name
theme: null
markdown: kramdown

collections:
  specs:
    output: true
    permalink: /specs/:path/     # /specs/0001-ssc/
