title: VoltMX Design Specs
url: "https://pranavwani.github.io"     # domain
baseurl: "/design-spec-v1"              # repo name for project sites

# add/merge these keys
collections:
  specs:
    output: true
    permalink: /specs/:path/
  draft_specs:
    output: true
    permalink: /drafts/:path/

# sensible defaults for draft pages
defaults:
  - scope: { path: "_draft_specs", type: "draft_specs" }
    values:
      layout: spec
      nav_title: "Overview"
      nav_order: 0

# optional: Jira base for Epic links
jira:
  base_url: https://hclsw-jiracentral.atlassian.net/browse

repo_url: "https://github.com/pranavwani/design-spec-v1"

# Config keys for PR Conversations module
github_oauth_client_id: "Ov23licZG0fDmqjaq11H"     # from GitHub OAuth App
api_base: "https://design-specs-api.vercel.app" # your serverless backend base URL
repo_owner: "pranavwani"
repo_name: "design-spec-v1"