name: "New Design Spec"
description: "Propose a new design spec"
title: "[Spec] <short title>"
labels: ["spec:proposal"]
body:
  - type: input
    id: title
    attributes: { label: "Spec title", placeholder: "Flutter SDK" }
    validations: { required: true }
  - type: dropdown
    id: status
    attributes: { label: "Initial status", options: ["in-progress"] }
  - type: textarea
    id: summary
    attributes: { label: "Summary (1–2 paragraphs)" }
    validations: { required: true }
  - type: checkboxes
    id: docs
    attributes:
      label: "Artifacts to include"
      options:
        - label: "HLD"
        - label: "LLD"
        - label: "API"
        - label: "UX"
  - type: input
    id: owner
    attributes: { label: "Owner (GitHub handle)" }
    validations: { required: true }
