name: "Update Existing Design Spec"
description: "Propose an update to an existing spec (bugfix, enhancement, or major revision)"
title: "[Update] <family> v<major> — <short summary>"
labels: ["spec:update"]
body:
  - type: input
    id: spec_ref
    attributes:
      label: "Which spec are you updating?"
      description: "Format: <family> v<major>. Example: flutter-sdk v1"
      placeholder: "flutter-sdk v1"
    validations:
      required: true

  - type: dropdown
    id: bump
    attributes:
      label: "Semantic version bump for spec_version"
      description: "How significant is this spec change?"
      options: [patch, minor, major]
      default: 0
    validations:
      required: true

  - type: dropdown
    id: promote
    attributes:
      label: "Stage change (optional)"
      description: "Promote stage after merge (enforces dev→stg→prod)"
      options:
        - (no change)
        - promote:stg
        - promote:prod
      default: 0

  - type: textarea
    id: motivation
    attributes:
      label: "Why is this update needed?"
      description: "Context for the change"
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "Scope of changes"
      description: "List what will be updated (files/sections)"
      placeholder: "- index.md summary\n- api.md: adjust POST /users payload"
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: "Risks or considerations"
      description: "Breaking changes, migrations, dependencies"

  - type: checkboxes
    id: artifacts
    attributes:
      label: "Docs affected"
      options:
        - label: "index.md (main spec)"
        - label: "hld.md"
        - label: "lld.md"
        - label: "api.md"
        - label: "ux.md"

  - type: input
    id: owner
    attributes:
      label: "Update owner (GitHub handle)"
      placeholder: "@your-handle"
    validations:
      required: true
